import requests
from config import GITHUB_API, get_github_headers


# Files to skip during review (auto-generated, not worth reviewing)
SKIP_FILES = [
    "package-lock.json", "yarn.lock", "poetry.lock",
    ".min.js", ".min.css", ".map", "__pycache__",
    "migrations/", ".pyc", "dist/", "build/"
]

def should_skip(filename: str) -> bool:
    return any(skip in filename for skip in SKIP_FILES)


def get_pr_diff(token: str, owner: str, repo: str, pr_number: int) -> dict:
    """
    Fetch the diff of a PR — only changed lines, not entire files.
    Returns a summary of what changed.
    """
    # Get PR metadata
    pr_resp = requests.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}",
        headers=get_github_headers(token)
    )
    if pr_resp.status_code != 200:
        return {"success": False, "error": pr_resp.json().get("message", "PR not found")}

    pr = pr_resp.json()

    # Get list of changed files
    files_resp = requests.get(
        f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/files",
        headers=get_github_headers(token)
    )
    if files_resp.status_code != 200:
        return {"success": False, "error": "Could not fetch PR files"}

    files = files_resp.json()

    # Filter out auto-generated files
    reviewable_files = [f for f in files if not should_skip(f["filename"])]
    skipped_files = [f["filename"] for f in files if should_skip(f["filename"])]

    # Build a compact diff summary (token efficient)
    diff_summary = []
    total_additions = 0
    total_deletions = 0

    for f in reviewable_files[:10]:  # max 10 files to stay within token limits
        additions = f.get("additions", 0)
        deletions = f.get("deletions", 0)
        total_additions += additions
        total_deletions += deletions

        patch = f.get("patch", "")

        # Trim very large patches to save tokens
        if len(patch) > 2000:
            patch = patch[:2000] + "\n... (truncated for brevity)"

        diff_summary.append({
            "file": f["filename"],
            "status": f["status"],  # added, modified, deleted
            "additions": additions,
            "deletions": deletions,
            "patch": patch
        })

    return {
        "success": True,
        "pr_title": pr["title"],
        "pr_body": pr.get("body", ""),
        "author": pr["user"]["login"],
        "base_branch": pr["base"]["ref"],
        "head_branch": pr["head"]["ref"],
        "total_files_changed": len(files),
        "reviewable_files": len(reviewable_files),
        "skipped_files": skipped_files,
        "total_additions": total_additions,
        "total_deletions": total_deletions,
        "diff": diff_summary,
        "pr_url": pr["html_url"]
    }


def get_pr_review_prompt(diff_data: dict) -> str:
    """
    Build a compact prompt for the LLM to review the PR.
    Designed to be token-efficient.
    """
    files_text = ""
    for f in diff_data["diff"]:
        files_text += f"\n--- {f['file']} ({f['status']}, +{f['additions']} -{f['deletions']}) ---\n"
        if f["patch"]:
            files_text += f["patch"] + "\n"

    prompt = f"""Review this GitHub Pull Request and provide:
1. A brief summary of what changed
2. Any bugs, security issues, or missing error handling you notice
3. Whether tests are present or needed
4. An auto-generated PR description

PR: "{diff_data['pr_title']}"
From: {diff_data['head_branch']} → {diff_data['base_branch']}
Files changed: {diff_data['total_files_changed']} (+{diff_data['total_additions']} -{diff_data['total_deletions']} lines)

CODE CHANGES:
{files_text}

Keep your review concise and actionable. Format it clearly with sections."""

    return prompt


def post_review_comment(token: str, owner: str, repo: str, pr_number: int, review: str) -> dict:
    """Post the AI review as a comment on the PR."""
    comment_body = f"## 🤖 AI Code Review\n\n{review}\n\n---\n*Review generated by GitHub Agent*"

    resp = requests.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/issues/{pr_number}/comments",
        json={"body": comment_body},
        headers=get_github_headers(token)
    )
    data = resp.json()
    if resp.status_code == 201:
        return {"success": True, "comment_url": data["html_url"]}
    return {"success": False, "error": data.get("message", "Failed to post comment")}
